export const WARRANTY_ABI = [
  {
    inputs: [
      {
        components: [
          { internalType: 'string', name: 'paytmTxnId', type: 'string' },
          { internalType: 'string', name: 'productName', type: 'string' },
          { internalType: 'string', name: 'productSerial', type: 'string' },
          { internalType: 'string', name: 'brand', type: 'string' },
          { internalType: 'string', name: 'modelNumber', type: 'string' },
          { internalType: 'address', name: 'customerAddress', type: 'address' },
          { internalType: 'uint256', name: 'purchaseAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'warrantyMonths', type: 'uint256' },
        ],
        internalType: 'struct PaytmWarranty.MintWarrantyInput',
        name: 'input',
        type: 'tuple',
      },
    ],
    name: 'mintWarranty',
    outputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'getWarranty',
    outputs: [
      {
        components: [
          { internalType: 'string', name: 'paytmTxnId', type: 'string' },
          { internalType: 'string', name: 'productName', type: 'string' },
          { internalType: 'string', name: 'productSerial', type: 'string' },
          { internalType: 'string', name: 'brand', type: 'string' },
          { internalType: 'string', name: 'modelNumber', type: 'string' },
          { internalType: 'address', name: 'customerAddress', type: 'address' },
          { internalType: 'uint256', name: 'purchaseAmount', type: 'uint256' },
          { internalType: 'uint256', name: 'warrantyMonths', type: 'uint256' },
          { internalType: 'uint256', name: 'purchaseDate', type: 'uint256' },
          { internalType: 'uint256', name: 'expiryDate', type: 'uint256' },
          { internalType: 'uint8', name: 'status', type: 'uint8' },
          { internalType: 'string', name: 'vendorName', type: 'string' },
        ],
        internalType: 'struct PaytmWarranty.WarrantyData',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'claimWarranty',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'from', type: 'address' },
      { internalType: 'address', name: 'to', type: 'address' },
      { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
    ],
    name: 'safeTransferFrom',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'owner', type: 'address' },
      { internalType: 'uint256', name: 'index', type: 'uint256' },
    ],
    name: 'tokenOfOwnerByIndex',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalSupply',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
    name: 'ownerOf',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'vendors',
    outputs: [
      { internalType: 'bool', name: 'registered', type: 'bool' },
      { internalType: 'string', name: 'name', type: 'string' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'tokenId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'customer', type: 'address' },
      { indexed: false, internalType: 'string', name: 'paytmTxnId', type: 'string' },
    ],
    name: 'WarrantyMinted',
    type: 'event',
  },
]
